package:
  name: soften
  version: 0.0.1

source:
  fn: soften-0.0.1.tar.gz
  url: https://github.com/dfroger/soften/archive/0.0.1.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

about:
  home: https://github.com/dfroger/soften
  license: GNU GPL v3
